# Generated by Django 6.0.1 on 2026-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendingregistration_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='household_passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='household_search_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='household_share_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
