# Generated by Django 6.0.1 on 2026-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_household_passcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
