# Generated by Django 6.0.1 on 2026-01-29 15:48

from django.db import migrations

LOCATIONS = [
    "attic",
    "garage",
    "basement",
    "guest room",
    "master bedroom",
    "hallway closet",
    "other",
]

def populate_locations(apps, schema_editor):
    Location = apps.get_model('containers', 'Location')
    for location_name in LOCATIONS:
        Location.objects.create(name=location_name)

class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_locations),
    ]
