# Generated by Django 6.0.1 on 2026-02-07 01:12

import containers.models
import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    ContainerPhoto = apps.get_model('containers', 'ContainerPhoto')
    for photo in ContainerPhoto.objects.all():
        photo.uuid = uuid.uuid4()
        photo.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_populate_locations'),
    ]

    operations = [
        # Step 1: Add uuid field as nullable
        migrations.AddField(
            model_name='containerphoto',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids, migrations.RunPython.noop),
        # Step 3: Make uuid non-nullable and unique
        migrations.AlterField(
            model_name='containerphoto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Step 4: Update image upload path
        migrations.AlterField(
            model_name='containerphoto',
            name='image',
            field=models.ImageField(upload_to=containers.models.container_photo_path),
        ),
    ]
