# Generated by Django 6.0.1 on 2026-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_containerphoto_uuid_alter_containerphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
