# Generated by Django 6.0.1 on 2026-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_container_is_password_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='owner_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
